### ISSUE TITLE
Starting Docker container Exception: Cannot find required server file: accServer.exe.

### ISSUE THREAD

**Issue by Danielvr** [gotzl/accservermanager#19]
Hi Gotzl,

I want to run your application but when I want to run the docker container I run into an issue. I get the error "Exception: Cannot find required server file: accServer.exe."

My own volume is ACCGotzl\data\server and in server it has accServer.exe -> ACCGotzl\data\server\accServer.exe
How is it possible that it isn't able to find it. 

I run Docker in Synology

The volume is DockerSSD/ACCGotzl/data/server -- /server
DockerSSD/ACCGotzl/data/server constains DockerSSD/ACCGotzl/data/server/accServer.exe

I hope you can help me why it isn't starting.

Using latest version from docker hub.

**Comment by gotzl** [comment]
Hi,
not sure what the issue is here. I've just used a dsmdemo instance to test for myself. I was able to start the app. The steps I did
* created directory 'server', created directory 'server/cfg'
* uploaded the contents (both the .exe in server/ and the *.json files in server/cfg)
* created the docker container, added the 'server/' directory with mount path '/server/
* added environment variables 'SECRET_KEY' with a random generated word and 'ALLOWED_HOSTS' (the latter I don't know how to correctly set in synology, though...)

After that, the container instance was running.

Next steps would have been to run the following in the container:
* python3 manage.py migrate
* python3 manage.py createsuperuser

But my time was up....
Sorry that I don't have a clue what's going wrong on your end, but at least I could show that it should in fact work ...

**Comment by Danielvr** [comment]
Hi Gotzl,

I was stupid. After putting the files on the server I needed to change the permission of the volume folder. I use links instead of volumes. But now it works. Thanks for the great work!

**Comment by Danielvr** [comment]
I have now something different. Everytime when I start the server it starts fine. I also can find the server in de server list search function. It had a password on it. But everytime when I and others want to connect ACC complete freeze and you only hear the sound continue. Any clue what it can be. When I run the server on the computer itself it works.

**Comment by gotzl** [comment]
Glad you got further ;)
The new issue might be a network traffic issue... UDP/TCP traffic drop, inwards or outwards. Can you verify that both UDP and TCP ports are properly opened an routed to the container? And that the packets are not dropped somewhere?

**Comment by Danielvr** [comment]
Hi gotzl,

Check the new created issue. All the ports are correctly opened and I don't see anything strange in the logs.
